name: Rust CI with Artifacts

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable
    
    - name: Build release
      run: cargo build --release
    
    - name: Upload binary artifact
      uses: actions/upload-artifact@v4
      with:
        name: release-binaries
        path: target/release/
        if-no-files-found: error
